### ISSUE TITLE
Unable to replicate output of tutorials for SCVI and SCANVI

### ISSUE THREAD

**Issue by reschandreas** [theislab/scarches#107]
Hello!

I've been trying to run the (SVCI and scANVI) tutorials given in your documentation but am unable to produce the exact same output as documented. I tried running the notebooks in jupyter and manually with Python, but I never receive the same scatterplot. The SCANVI pipeline further seems to have a typo in [10] as it requires `scarches.models.SCVI.setup_anndata` instead of ` scarches.models.SCANVI.setup_anndata` to run without compile errors.
Additionally I don't get the exact same output when running the pipelines, I've never seen messages like `INFO     Using labels from adata.obs["cell_type"]`, thus I suppose I'm either running a very different scarches version (I am running 0.5.1 and since yesterday 0.5.2) or I am not setting a flag that produces these outputs. Also the labels don't get recognized so the output for the lines 
```
print("Labelled Indices: ", len(scanvae._labeled_indices))
print("Unlabelled Indices: ", len(scanvae._unlabeled_indices))
```
 is 0 for both indices.

I uploaded my notebooks here for [scvi](https://gist.github.com/reschandreas/c4b0e37211ba1ab63fb313e8d49ddaf9) and [scanvi](https://gist.github.com/reschandreas/0999e6eaaffd5e6f1b115f65ec115166) to show you the output that I get.

My question is, is the documentation that outdated, am I working with a different dataset and the results are valid, or am I doing something wrong?

**Comment by reschandreas** [comment]
Hi! Thanks for the reply.
I tried the quick fix but It still seems as though the model does not find the labeled indices.
[Here](https://gist.github.com/reschandreas/b2e1c320badb11471ca17a3cba5ff141) is my notebook with your suggestions.

**Comment by Koncopd** [comment]
Yes, i see , this seems to be a bug in the later versions of scvi, reported here
https://github.com/scverse/scvi-tools/issues/1514
I can't do anything until it is fixed in scvi.

**Comment by reschandreas** [comment]
Could you please tell me in the meantime with which combination of scarches and scvi-tools versions it worked? Thanks!

**Comment by Koncopd** [comment]
The tutorials work fine with scvi-tools==0.14.3 and the latest scarches.

**Comment by adamgayoso** [comment]
Indeed we have a bug on our end that doesn't seem to affect the inference, but @Koncopd would be great if you removed any access/printing of these private attrs. It's not currently necessary to do what you're doing anymore

**Comment by Koncopd** [comment]
@adamgayoso i am not sure what do you mean by "doesn't seem to affect the inference". Now it doesn't take the lables into account during training. Anyways, it will be fixed soon, as i see. I can remove but then how we can be sure that the labels are really used during the training. Maybe some api for this? As you see it is important to be sure.

**Comment by adamgayoso** [comment]
It does indeed take the labeled cells even with this "bug". The bug only affects one aspect which is label subsampling during minibatching (non default anyway).

The actual data splits occur here:

https://github.com/scverse/scvi-tools/blob/cc38acc8d72d1b03ef3592cb1699114dcd040438/scvi/dataloaders/_data_splitting.py#L159

Therefore, it would be great to remove this code from your tutorial

**Comment by adamgayoso** [comment]
There are other aspects of this tutorial that are out of date, due to various fixes we made in the last few months. Currently up to date tutorial can be found here:

https://docs.scvi-tools.org/en/stable/tutorials/notebooks/scarches_scvi_tools.html

**Comment by reschandreas** [comment]
With the new version of scvi-tools 0.16.1 the labels get recognized again.

**Comment by M0hammadL** [comment]
ok then I would close this.
