### ISSUE TITLE
Query data batch ID

### ISSUE THREAD

**Issue by Nusob888** [theislab/scarches#109]
Thank you for the brilliant work. 

I hope you may be able to help with a query (pun not intended):

For query datasets, can multiple queries be merge into one query object? 
Or 
Is it better to query each individual datasets and update the model per dataset?

If the answer is that merging query datasets is acceptable, then I cannot see how batch is accounted for when the model is re-trained with the query dataset. Am I right in interpreting this to mean that batch identification as a covariate is not required when querying multiple datasets which have been concatenated?

Many thanks for any help with this matter

**Comment by M0hammadL** [comment]
hi, thx for using scarches. 

- yes they can be merged and queried at once, we suggest assigning a unique batch id to each on of them to properly remove batch effects.
-  theoretically, the order should not affect the training and the quality/
- if merged, then please assign a unique id to each dataset

**Comment by Nusob888** [comment]
Brilliant, thank you!
