### ISSUE TITLE
Error when creating SCANVI model with tutorial

### ISSUE THREAD

**Issue by paupuigdevall** [theislab/scarches#118]
I'm trying to reproduce the semi-supervised pipeline in here [https://scarches.readthedocs.io/en/latest/scanvi_surgery_pipeline.html], but the pipeline is failing when trying to build the model using the reference dataset:

>>> sca.models.SCANVI.setup_anndata(source_adata, batch_key=condition_key, labels_key=cell_type_key)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: setup_anndata() missing 1 required positional argument: 'unlabeled_category'

I'm using python 3.9.13, packaged by conda-forge. I tried installing other versions of python and installing scarches both with PyPI and Development, but the error persists. Not sure if I'm doing something wrong. Could you please help me understand this error?

**Comment by Koncopd** [comment]
Hi, @paupuigdevall i will check and let you know, probably we need to update the tutorials for new scanvi versions.

**Comment by JLTrincado** [comment]
Dear authors,

just a suggestion. Regarding Semi-supervised surgery pipeline with SCANVI tutorial, if data is set up with SCANVI, the model has to be SCANVI. But in the tutorial, the setup is with SCANVI but SCVI model is used. This throws an error:

```
vae = sca.models.SCVI(
    source_adata,
    n_layers=2,
    encode_covariates=True,
    deeply_inject_covariates=False,
    use_layer_norm="both",
    use_batch_norm="none",
)

ValueError: Please set up your AnnData with SCVI.setup_anndata first. It appears the AnnData object has been setup with a different model.
```

Thanks and congrats for this awesome work,
Juan L.

**Comment by M0hammadL** [comment]
@Koncopd

**Comment by Koncopd** [comment]
In the notebook we have specified the version of scvi-tools used to run it, please try with this version.
https://github.com/theislab/scarches/blob/master/notebooks/scanvi_surgery_pipeline.ipynb
Feel free to reopen it still doesn't work.
