### ISSUE TITLE
HVG query vs ref

### ISSUE THREAD

**Issue by Nusob888** [theislab/scarches#119]
Hi, 

Are there any recommendations on how to mismatch/process query datasets where not all HVGs of the reference are within the query? 

Should we be zero padding missing data?

**Comment by M0hammadL** [comment]
Hi, for now i would say zero padding is the best way to do it

**Comment by Nusob888** [comment]
Brilliant, thanks. Are there any future plans on a more nuanced way to take this into account?
Have you found zero padding to influence the transfer certainty?

**Comment by M0hammadL** [comment]
indeed see supplementary figure in scarches paper, more zeros in query worse integration and thus uncalibrated (un)certainty
