### ISSUE TITLE
Annotation for cancer cells？

### ISSUE THREAD

**Issue by bitcometz** [theislab/scarches#121]
Hello,
If I use cells from normal sample as reference, can I use scarches to annotate the cancer cells in the tumor sample ?

Thanks !!!

**Comment by M0hammadL** [comment]
Hey, yes if there are overlapping cell-type between your cancer and healthy  samples then you could do that, i would suggest to have look at our treearches pipeline (see tutorials)

**Comment by bitcometz** [comment]
thanks !!!
