### ISSUE TITLE
scipy.stats.itemfreq is deprecated and removed in Version 1.9.0 of scipy

### ISSUE THREAD

**Issue by hermannschwaerzlerUIBK** [theislab/scarches#122]
I tried to install `scarches` in a conda environment I created like this:

`conda create -c conda-forge -n sca python=3.8 numpy gdown scanpy pytorch pandas matplotlib seaborn pillow scipy`

After activating that environment and running `pip install -U scarches` I got this:
```
python --version
Python 3.8.13

python
Python 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:04:18) 
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scarches as sca
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/lib/python3.8/site-packages/scarches/__init__.py", line 1, in <module>
    from . import dataset, metrics, trainers, models, zenodo, plotting, utils
  File "[...]/lib/python3.8/site-packages/scarches/metrics/__init__.py", line 1, in <module>
    from .metrics import entropy_batch_mixing, knn_purity, nmi, asw
  File "[...]/lib/python3.8/site-packages/scarches/metrics/metrics.py", line 3, in <module>
    from scipy.stats import itemfreq, entropy
ImportError: cannot import name 'itemfreq' from 'scipy.stats' ([...]/lib/python3.8/site-packages/scipy/stats/__init__.py)
```

This is due to the fact that `itemfreq` is deprecated (see https://docs.scipy.org/doc/scipy-1.8.1/reference/generated/scipy.stats.itemfreq.html) and is not available any more in versions 1.9.0 and newer of `scipy`.

My solution for this problem was to remove the previously created conda-environment and re-create it with
`conda create -c conda-forge -n sca python=3.8 numpy gdown scanpy pytorch pandas matplotlib seaborn pillow scipy=1.8.1`
i.e. by downgrading `scipy` to the latest version still containing `itemfreq`.

A better solution might be to change `metrics/metrics.py` (https://github.com/theislab/scarches/blob/master/scarches/metrics/metrics.py#L106)?

**Comment by Koncopd** [comment]
Now should be fixed.
