### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by v-mahughes** [theislab/scarches#123]
I cloned the repo and ran python3 setup.py install in the scarches directory, but I run into this error: 

Installed /usr/local/lib/python3.8/dist-packages/scArches-0.5.4-py3.8.egg
Processing dependencies for scArches==0.5.4
error: rich 12.5.1 is installed but rich~=11.1 is required by {'flax'}

**Comment by Koncopd** [comment]
We don't require flax, it is probably scvi-tools installation error. Are you able to install scvi-tools separately?
