### ISSUE TITLE
vae.train() error

### ISSUE THREAD

**Issue by sukyorsuki** [theislab/scarches#128]
I have a model trained on ref_data with cell type labels

vae = sca.models.SCANVI(
    ref_data,
    "Unknown",
    n_layers=2,
    encode_covariates=True,
    deeply_inject_covariates=False,
    use_layer_norm="both",
    use_batch_norm="none"
   # use_cuda=True
)

vae.train(
 max_epochs= 400,
       use_gpu= False
 )

File c:\Python\lib\site-packages\scvi\model\_scanvi.py:393, in SCANVI.train(self, max_epochs, n_samples_per_label, check_val_every_n_epoch, train_size, validation_size, batch_size, use_gpu, plan_kwargs, **trainer_kwargs)
    382     trainer_kwargs["callbacks"] = sampler_callback
    384 runner = TrainRunner(
    385     self,
    386     training_plan=training_plan,
   (...)
    391     **trainer_kwargs,
    392 )
--> 393 return runner()

File c:\Python\lib\site-packages\scvi\train\_trainrunner.py:72, in TrainRunner.__call__(self)
     69 if hasattr(self.data_splitter, "n_train"):
     70     self.training_plan.n_obs_training = self.data_splitter.n_train
---> 72 self.trainer.fit(self.training_plan, self.data_splitter)
     73 self._update_history()
     75 # data splitter only gets these attrs after fit
...
---> 58     return torch.as_tensor(data)
     59 elif isinstance(data, collections.abc.Mapping):
     60     try:

RuntimeError: Could not infer dtype of numpy.float32

How to fix this problem? Any advise will be greatly appreciated!

**Comment by Koncopd** [comment]
Hi, what is the version of scvi-tools?

**Comment by sukyorsuki** [comment]
scvi-tools==0.14.6

**Comment by Koncopd** [comment]
Hi, about scanVI and scVI i would suggest to ask on scvi github, as we only reexport these models.
https://github.com/scverse/scvi-tools
