### ISSUE TITLE
A issue of scANVI

### ISSUE THREAD

**Issue by melancholy12** [theislab/scarches#129]
Here is my error. I am struggling on how to fix it.
![image](https://user-images.githubusercontent.com/97800939/194788231-c6c63b60-2593-4152-ad8d-e26f9d092eb3.png)
![image](https://user-images.githubusercontent.com/97800939/194788239-20a6b8de-7ffd-4e8d-a7cf-9d18439c2102.png)

**Comment by Koncopd** [comment]
Hi, about scanVI and scVI i would suggest to ask on scvi github, as we only reexport these models.
https://github.com/scverse/scvi-tools
