### ISSUE TITLE
reference model question re: conditions

### ISSUE THREAD

**Issue by bkmartinjr** [theislab/scarches#14]
In the case where a reference model is published, all downstream users who want to transfer that to their query data must know both the gene names and conditions for training their derivative model.  Gene names are easily accessed, as they are embedded in the model.  Condition labels are also saved, but the model does not include information about _how_ the condition labels were generated (eg, the original `condition_key`, or in more complex cases, a condition derived from multiple obs columns).

In the reference model re-use cases, do you have guidance on how model publishers should inform query users of proper condition label generation (or minimally, the condition key)?

Side note: it would be helpful to have a sample note book which shows best practices for the "query" user - ie, once you have a reference model, how you normalize, train, classify, etc with only the query dataset in hand.

Thanks again!

**Comment by M0hammadL** [comment]
Yes, we also thought about that too, right now model publishers can explain in `additional description` field [here](https://docs.google.com/forms/d/1_j65-sRbHAGZsfDAXGVWLw4yEDe1czdtTCypfS6SPkw/edit?ts=5f02c493). I think this would be the best way for people to clarify this? It would be great for every user to attach a notebook to their model submission form.


regarding your side note, we have the[ pipe-line](https://scarches.readthedocs.io/en/latest/pancreas_pipeline.html) tutorial and [this](https://scarches.readthedocs.io/en/latest/zenodo_pancreas_from_pretrained.html) tutorial for query users. I will try to make the second one more illustrative in the aspects you mentioned.

**Comment by ambrosejcarr** [comment]
HI Mohammad - thanks for the clarification. We're thinking about a slightly different use case where there is no computational biologist available to tweak the model. We're wondering if you want a non-expert to be able to use this package to transfer labels, extending what they can do with scanpy from identifying reasonable clusters of cells and marker genes to recommending labels for cell types. 

One way this might work: 
* There would be some basic schema, such as what you've been building in `sfaria` or what we're working on in `cellxgene`, 
* Users can browse models for a tissue and download them, 
* Condition key would either match a column from the schema, or be a function that constructs the appropriate query column from fields in the schema. 
* input parameters for label transfer are just a query dataset (containing at least condition_key or required metadata to create it) and a model. The package does the rest.

**Comment by M0hammadL** [comment]
hi @ambrosejcarr 
We are working on a  website so that you can browse models and even project data on that. However, integrating with `cellxgene` might take some time. Could we get some people from CZI to help us with this?

**Comment by ambrosejcarr** [comment]
@M0hammadL we're very interested in this idea and would be able to spend some time on it. Could we set up a call? I'd like to hear more about your vision for how this would work.

**Comment by M0hammadL** [comment]
@bkmartinjr sure, that would be great? maybe continue via email?
