### ISSUE TITLE
Not seeing scPoli in scarches.models

### ISSUE THREAD

**Issue by yanwu2014** [theislab/scarches#150]
I'm not seeing scpoli in `scarches.models`, does it need to be imported here: https://github.com/theislab/scarches/blob/master/scarches/models/__init__.py?

**Comment by M0hammadL** [comment]
Hi see here: https://github.com/theislab/scarches/tree/master/scarches/models/scpoli

**Comment by yanwu2014** [comment]
Ah sorry that was an issue on my end, I can import `scarches.models.scpoli` now!
