### ISSUE TITLE
Matrix multiplication error in scpoli_model.classify

### ISSUE THREAD

**Issue by mariemoullet** [theislab/scarches#161]
Hello! I am trying to use scPoli to integrate a labelled and unlabelled data. I've managed to train the model and visualize the cell and latent embeddings in UMAP, but I get an error when calling `scpoli_model.classify()` : 

`RuntimeError: mat1 and mat2 shapes cannot be multiplied (512x27254 and 2000x128) `

Based on the error message, it seems to be getting stuck at `latent = self.get_latent(x, c)` [here](https://github.com/theislab/scarches/blob/c21492d409150cec73d26409f9277b3ac971f4a7/scarches/models/scpoli/scpoli.py#L272)

I am using 2000 HVG to build the model, and I have 28614 labelled cells and 27254 unlabelled cells. Do you have any sense of what could be going wrong?

Thank you very much for your help!

**Comment by cdedonno-immunai** [comment]
Hi @mariemoullet, could you paste here the entire error log, so I can look into it?

**Comment by cdedonno** [comment]
Hi @mariemoullet, could you paste the entire error log here?

**Comment by mariemoullet** [comment]
Thank you so much for your quick reply! Here is the function call : 
` results_dict_q = scpoli_model.classify(
    x=query_adata.X, 
    c=query_adata.obs[condition_key]
) `

And here is the error log: 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[22], line 1
----> 1 results_dict_q = scpoli_model.classify(
      2     x=query_adata.X, 
      3     c=query_adata.obs[condition_key]
      4 )
      6 preds_q = results_dict_q[cell_type_key[0]]['preds']
      7 probs_q = results_dict_q[cell_type_key[0]]['probs']

File /opt/conda/envs/scarches_dev2/lib/python3.8/site-packages/scarches/models/scpoli/scpoli_model.py:388, in scPoli.classify(self, x, c, prototype, get_prob, log_distance)
    380     pred, prob, weighted_distance = self.model.classify(
    381         x[batch, :].to(device),
    382         prototype=prototype,
   (...)
    385         log_distance=log_distance,
    386     )
    387 else:  # default routine, classify cell by cell
--> 388     pred, prob, weighted_distance = self.model.classify(
    389         x[batch, :].to(device),
    390         c[batch].to(device),
    391         prototype=prototype,
    392         classes_list=prototypes_idx,
    393         get_prob=get_prob,
    394         log_distance=log_distance,
    395     )
    396 preds += [pred.cpu().detach()]
    397 uncert += [prob.cpu().detach()]

File /opt/conda/envs/scarches_dev2/lib/python3.8/site-packages/scarches/models/scpoli/scpoli.py:272, in scpoli.classify(self, x, c, prototype, classes_list, get_prob, log_distance)
    270     latent = x
    271 else:
--> 272     latent = self.get_latent(x, c)
    274 dists = euclidean_dist(latent, self.prototypes_labeled["mean"][classes_list, :])
    276 # Idea of using euclidean distances for classification

File /opt/conda/envs/scarches_dev2/lib/python3.8/site-packages/scarches/models/scpoli/scpoli.py:326, in scpoli.get_latent(self, x, c, mean)
    324     c = c.long()
    325     embed_c = self.embedding(c)
--> 326     z_mean, z_log_var = self.encoder(x_, embed_c)
    327 else:
    328     z_mean, z_log_var = self.encoder(x_)

File /opt/conda/envs/scarches_dev2/lib/python3.8/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File /opt/conda/envs/scarches_dev2/lib/python3.8/site-packages/scarches/models/scpoli/scpoli.py:433, in Encoder.forward(self, x, batch)
    431     x = torch.cat((x, batch), dim=-1)
    432 if self.FC is not None:
--> 433     x = self.FC(x)
    434 means = self.mean_encoder(x)
    435 log_vars = self.log_var_encoder(x)

File /opt/conda/envs/scarches_dev2/lib/python3.8/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File /opt/conda/envs/scarches_dev2/lib/python3.8/site-packages/torch/nn/modules/container.py:139, in Sequential.forward(self, input)
    137 def forward(self, input):
    138     for module in self:
--> 139         input = module(input)
    140     return input

File /opt/conda/envs/scarches_dev2/lib/python3.8/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File /opt/conda/envs/scarches_dev2/lib/python3.8/site-packages/scarches/models/scpoli/scpoli.py:623, in CondLayers.forward(self, x)
    621 else:
    622     expr, cond = torch.split(x, [x.shape[1] - self.n_cond, self.n_cond], dim=1)
--> 623     out = self.expr_L(expr) + self.cond_L(cond)
    624 return out

File /opt/conda/envs/scarches_dev2/lib/python3.8/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

File /opt/conda/envs/scarches_dev2/lib/python3.8/site-packages/torch/nn/modules/linear.py:114, in Linear.forward(self, input)
    113 def forward(self, input: Tensor) -> Tensor:
--> 114     return F.linear(input, self.weight, self.bias)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (512x27254 and 2000x128)

**Comment by cdedonno** [comment]
It seems there is some problem happening in one of the `CondLayers` of the encoder, but I don't understand what might be causing the mismatch. Could you show me the output of `print(query_adata.X.shape)` and `print(train_adata.X.shape)`? And also the model description that is printed when you initialize your scpoli model.

**Comment by mariemoullet** [comment]
It turns out the mismatch was entirely my fault, when I defined `query_adata` I accidentally used an object which hadn't been filtered for HVG sorry about that! Updating `query_adata` solved the matrix multiplication issue, I am now running into an error to do with `class_list` (pasted below)

sorry about the confusion thank you so much for your help! 


`results_dict_q = scpoli_model.classify(
    x=query_adata.X, 
    c=query_adata.obs[condition_key] `



---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[29], line 1
----> 1 results_dict_q = scpoli_model.classify(
      2     x=query_adata.X, 
      3     c=query_adata.obs[condition_key]
      4 )
      6 preds_q = results_dict_q[cell_type_key[0]]['preds']
      7 probs_q = results_dict_q[cell_type_key[0]]['probs']

File /opt/conda/envs/scarches_dev2/lib/python3.8/site-packages/scarches/models/scpoli/scpoli_model.py:388, in scPoli.classify(self, x, c, prototype, get_prob, log_distance)
    380     pred, prob, weighted_distance = self.model.classify(
    381         x[batch, :].to(device),
    382         prototype=prototype,
   (...)
    385         log_distance=log_distance,
    386     )
    387 else:  # default routine, classify cell by cell
--> 388     pred, prob, weighted_distance = self.model.classify(
    389         x[batch, :].to(device),
    390         c[batch].to(device),
    391         prototype=prototype,
    392         classes_list=prototypes_idx,
    393         get_prob=get_prob,
    394         log_distance=log_distance,
    395     )
    396 preds += [pred.cpu().detach()]
    397 uncert += [prob.cpu().detach()]

File /opt/conda/envs/scarches_dev2/lib/python3.8/site-packages/scarches/models/scpoli/scpoli.py:274, in scpoli.classify(self, x, c, prototype, classes_list, get_prob, log_distance)
    271 else:
    272     latent = self.get_latent(x, c)
--> 274 dists = euclidean_dist(latent, self.prototypes_labeled["mean"][classes_list, :])
    276 # Idea of using euclidean distances for classification
    277 if get_prob == True:

TypeError: 'NoneType' object is not subscriptable

**Comment by cdedonno** [comment]
No problem at all. It seems that there are no initialized prototypes. Could you send me the function call you use to instantiate the model and train it? Also, can you try reinitializing the current notebook kernel you are using and try again? Sometimes multiple instantiations of the model can lead to these issues.

**Comment by mariemoullet** [comment]
Restarted the kernel and ran into the same error message, here is the code to instantiate the model and train it : 

`
scpoli_model = scPoli(
    adata=adata,
    condition_key=condition_key,
    cell_type_keys=cell_type_key,
    labeled_indices=labeled_idx,
    unknown_ct_names=['Unknown'],
    hidden_layer_sizes=[128, 128, 10],
    latent_dim=30,
    embedding_dim=5,
    inject_condition=['encoder', 'decoder']
)

early_stopping_kwargs = {
    "early_stopping_metric": "val_prototype_loss",
    "mode": "min",
    "threshold": 0,
    "patience": 20,
    "reduce_lr": True,
    "lr_patience": 13,
    "lr_factor": 0.1,
}

scpoli_model.train(
    n_epochs=100,
    pretraining_epochs=50,
    early_stopping_kwargs=early_stopping_kwargs,
    eta=1,
)

`

thank you so much for your help!

**Comment by cdedonno** [comment]
Looks all good to me. Hard to see what might be going wrong here. Are you sure the `labeled_idx` you are passing is correct?

**Comment by mariemoullet** [comment]
Yes just checked those and looks good!

**Comment by M0hammadL** [comment]
@mariemoullet  a link to HTML for the notebook might help to resolve the problem faster

**Comment by mariemoullet** [comment]
https://colab.research.google.com/drive/1ZhDqZifeLlA8R1u_8yb7ZfgBZ2RrWEwJ?usp=sharing

**Comment by M0hammadL** [comment]
@cdedonno, what could be the problem?

**Comment by cdedonno** [comment]
Still hard to understand, there is some unexpected behavior when training starts. This warning should not appear.

```
Warning: Labels in adata.obs[cell_type] is not a subset of label-encoder!
Therefore integer value of those labels is set to -1
```
@mariemoullet could you by any chance provide the data so I can reproduce the issue on my machine and debug?

**Comment by cdedonno** [comment]
I tried recreating a similar scenario with the dataset used in the demo but everything works fine on my end. @mariemoullet would you be ok for you to discuss this via email? we can arrange also a call if necessary
