### ISSUE TITLE
scPoli error of label transfer

### ISSUE THREAD

**Issue by melancholy12** [theislab/scarches#165]
The model trainning the query and reference goes fine. But when I do the label transfer, it showed error.
![image](https://user-images.githubusercontent.com/97800939/215811013-f3c281cd-bd29-4ed8-a6f2-d489542c9f89.png)
![image](https://user-images.githubusercontent.com/97800939/215811038-39ba671e-2df7-44b4-988a-9def6a20266f.png)
![image](https://user-images.githubusercontent.com/97800939/215811122-c20a0555-3794-489f-8abf-55bc8ef7eb23.png)
![image](https://user-images.githubusercontent.com/97800939/215811172-5efda678-3e7d-49dd-b519-63cbedcb0ed1.png)

**Comment by M0hammadL** [comment]
@cdedonno

**Comment by cdedonno** [comment]
Hi @melancholy12, it's hard to diagnose the problem with just this information. I suspect you might have some problems in either the `adata_query.obs[cell_type_key[i]]` column or the `preds` output by the model. Could you print them out?

**Comment by melancholy12** [comment]
@cdedonno Hello, because the query is from unknow dataset. We would like to do the mapping. Here is the results of adata_query.obs[cell_type_key[i]]. All of them are NaN.  By the way, how could I show the preds output by the model?

(https://user-images.githubusercontent.com/97800939/216486140-460b77bd-a00f-4ed9-a3be-d4dac552917d.png)

**Comment by melancholy12** [comment]
![image](https://user-images.githubusercontent.com/97800939/216486464-63f11a6b-7a8e-4300-abea-7a4961112469.png)

**Comment by cdedonno** [comment]
Well, if you don't have a labelled query then you can't compute the classification accuracy on your query dataset, that's why you're getting the error. The preds output by the model are stored in the `preds` variable in your cell 68.

**Comment by cdedonno** [comment]
Well, if you don't have a labelled query then you can't compute the classification accuracy on your query dataset, that's why you're getting the error. The preds output by the model are stored in the `preds` variable in your cell 68.

**Comment by melancholy12** [comment]
@cdedonno Hi Cdedonno, The last issue has been solved. Thanks a lot for your help. I have 2 more questions.
1. In order to use the scPoli, I should have the ground truth first to my adata_query dataset, right?
2. for scpoli_model = scPoli(
    adata=adata_ref,
    condition_key=condition_key,
    cell_type_keys=cell_type_key,
    embedding_dim=3,
), How can I set the batch (or samples) key?

**Comment by cdedonno** [comment]
Hi, glad to hear your issue was solved. Regarding your questions.

1. You do not need ground truth for your query dataset. You need it in order to compute the classification accuracy, but in a real world scenario you're likely not gonna have an annotated query. You can propagate the labels from the reference and then investigate if they make sense, or, if integration looks really good and classification accuracy on the reference was good, trust the model.
2. The samples key is the `condition_key` argument in the model call.
