### ISSUE TITLE
how to improve resolution

### ISSUE THREAD

**Issue by notimenocall** [theislab/scarches#17]
Hi team,

Thanks much for the great tool. I was able to install it pretty smoothly and run through with a public data set without errors (so far) based on the nicely documented tutorials.
One issue I have though is the separation of the cells. The object was previously analyzed with a standard Scanpy pipeline and now used to train the model. When I checked my latent_adata, the cell types are not separated as nicely as what they looked like before analyzed by Scanpy and many previously-seen smaller branches in the UMAP are now merged into a big blob.
I've tried following the 'tips' and tried different z_dimension (10 or 20),  architecture (from the default to [128,128,128,128]), alpha (down to even 0.000001), n_epochs (100, 150, 200), hvg (2k genes or 5k genes), but none seems to help. (loss_fn is always 'nb'.)
Any advice will be greatly appreciated! Thanks!

Best,
Xiao

**Comment by M0hammadL** [comment]
Hi Xiao, 

thanks for using the tool, Can you try using `loss_fn` = `sse` or `loss_fn` = `mse` and see the results?

**Comment by notimenocall** [comment]
Changing to sse recapitulates almost 100% of the result. Thank you very much for your advice.
