### ISSUE TITLE
scPoli get latent representations

### ISSUE THREAD

**Issue by melancholy12** [theislab/scarches#170]
I used 10-30 latent when I run scvi model. Where can I set the latent representations when I use the scPoli?
Thanks!

**Comment by cdedonno** [comment]
Hi @melancholy12, please refer to the [documentation](https://scarches.readthedocs.io/en/latest/api/models.html#scpoli). The parameter you're looking for is `latent_dim`.

**Comment by melancholy12** [comment]
Hi @cdedonno ,I only used scPoli for reference mapping. Can I only use it for data integration rather than mapping? For example, the single cell RNA seq data have a lot of components. I just want to do the data integration.
