### ISSUE TITLE
Documentation website failing to load

### ISSUE THREAD

**Issue by virpatel524** [theislab/scarches#184]
Good morning, 

I'm having issues getting the Docs to load. For instance this page fails to load on my laptop: [ScArches Models](https://www.scarches.org/en/latest/api/models.html). I've tried different wireless networks and even used the 5G network without WiFi on my phone to try to load it, but no luck. Can't think of any reasonable explanation as to why is this going on unless there are some kind of new United States sanctions against the Theis lab. 

Any tips? Some more immediate code I need is to save the output of my ExpiMap neural network training. It took several days so I want to make sure I don't lose it. A code snippet that can accomplish that would be lots of help until we are able to figure out the website issue. 

Appreciate your time.

Best,
Vir Patel
(Tata Lab, Duke U)

**Comment by virpatel524** [comment]
<img width="1320" alt="Screenshot 2023-04-03 at 9 47 14 AM" src="https://user-images.githubusercontent.com/6751282/229528987-81f5a21d-bdcd-4e50-89d0-bc92eed0fc80.png">

**Comment by Koncopd** [comment]
@virpatel524 thank you, we are checking what happened.

**Comment by Koncopd** [comment]
@virpatel524 it should be up now.
