### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'condition_keys'

### ISSUE THREAD

**Issue by yuxiaokang-source** [theislab/scarches#193]
I run the tutorial https://docs.scarches.org/en/latest/scpoli_surgery_pipeline.html, I get 
![image](https://github.com/theislab/scarches/assets/59059267/0b1e41eb-1e9c-47cb-8954-11c59bdc27e0)
,my environment is 
![image](https://github.com/theislab/scarches/assets/59059267/040690ac-2b32-4429-a47b-1b408b625cd4)

**Comment by cdedonno** [comment]
Hi, can you download the latest version (I think it's 0.5.9) and check if the issue persists?

**Comment by cdedonno** [comment]
The latest version is 0.5.9, as you can see from [PyPI](https://pypi.org/project/scArches/). Not sure why you are unable to install it. You can also work around this by installing the git repository directly using:

`pip install git+https://github.com/theislab/scarches.git`

**Comment by yuxiaokang-source** [comment]
> The latest version is 0.5.9, as you can see from [PyPI](https://pypi.org/project/scArches/). Not sure why you are unable to install it. You can also work around this by installing the git repository directly using:
> 
> `pip install git+https://github.com/theislab/scarches.git`
Thank you for your advice, I have installed scarches(0.5.9)  and run the tutorial successfully.
