### ISSUE TITLE
Install issue - no .yml in repo

### ISSUE THREAD

**Issue by james-cranley** [theislab/scarches#194]
Hi, just to say I can install scArches fine by pip, but following the instructions below (from https://docs.scarches.org/en/latest/installation.html) doesn't work because there is no `scarches_linux.yml` in the github repo

```
git clone https://github.com/theislab/scarches
cd scarches
conda env create -f envs/scarches_linux.yml
conda activate scarches
```

**Comment by Koncopd** [comment]
Sorry, it is `scarches_linux.yaml`, not `scarches_linux.yml`. I will edit.

**Comment by james-cranley** [comment]
great, thanks!
