### ISSUE TITLE
genes to include for query adata

### ISSUE THREAD

**Issue by notimenocall** [theislab/scarches#20]
Hi team,
This could be somewhat related to my previous issue but it may be easier to have it in a separate one. 
It seems like to train a new network based on a pre-trained scArches, query data set needs to have the same genes used as the reference data set, otherwise it errors. Is there a way to shrink or expand the gene sets for the training? I've added a bunch of 0 for genes missing in my query data set but are in the reference for now to avoid the error message. I can also imagine in some cases there will be genes with important features for query data sets but are not captured in the original training with the reference data sets. What should be the best practice?
Thanks,
Xiao

**Comment by M0hammadL** [comment]
Hi @notimenocall. The current ecosystem requires gene names to be the same. Thus, the query genes should be subsetted to the ones in reference otherwise set zero for the ones which are not available. For example, if you `x_ref = [g1, g2. g3] ` and your query has `x_qeury = [g1,g3]` then the `x_qeury ` should change to `x_qeury = [g1, 0, g3]`

**Comment by notimenocall** [comment]
Thanks for your reply and clarification. This is what I have been doing now. 
I am just thinking will this create bias, since the hvg are not selected based on the query data sets.

**Comment by M0hammadL** [comment]
yes, you are right. This might induce a bias. However, the assumption is the reference data is so rich and it hast most of the signal which is needed for that organ. Incorporating new genes that were not included in reference might not make that much sense if we never had that gene and will be hard if we had this gene and the gene did not make it to final training data after feature selection. I will think about it and see if we can find an intermediate solution in later updates.

**Comment by notimenocall** [comment]
It makes sense. Alternatively, will it help or hurt to include more hvg genes (> 5k?) when training the reference? Thank you.

**Comment by M0hammadL** [comment]
@notimenocall it depends on the organ or the complexity of the system you are working with, I would start with 2k and then go to 5k. For multi-tissue/species analysis higher genes are needed.

**Comment by notimenocall** [comment]
Good point. Thank you.
