### ISSUE TITLE
Fail to import scarches  

### ISSUE THREAD

**Issue by melancholy12** [theislab/scarches#202]
import scarches 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/tmp/ipykernel_119144/4038665422.py in <module>
----> 1 import scarches

~/anaconda3/lib/python3.9/site-packages/scarches/__init__.py in <module>
----> 1 from . import dataset, metrics, trainers, models, zenodo, plotting, utils, classifiers
      2 
      3 __author__ = ', '.join([
      4     'Mohammad Lotfollahi',
      5     'Sergei Rybakov',

~/anaconda3/lib/python3.9/site-packages/scarches/models/__init__.py in <module>
----> 1 from .trvae.trvae import trVAE
      2 from .trvae.trvae_model import TRVAE
      3 from .trvae.adaptors import Adaptor, attach_adaptors
      4 from .scgen.vaearith import vaeArith
      5 from .scgen.vaearith_model import scgen

~/anaconda3/lib/python3.9/site-packages/scarches/models/trvae/trvae.py in <module>
      7 
      8 from .modules import Encoder, Decoder
----> 9 from .losses import mse, mmd, zinb, nb
     10 from ._utils import one_hot_encoder
     11 from ..base._base import CVAELatentsModelMixin

~/anaconda3/lib/python3.9/site-packages/scarches/models/trvae/losses.py in <module>
----> 1 from scvi.distributions import NegativeBinomial
      2 import torch
      3 from torch.autograd import Variable
      4 from torch.distributions import Poisson
      5 import torch.nn.functional as F

ModuleNotFoundError: No module named 'scvi.distributions'

I cannot install scarches in python 3.9 because the torch 1.6.0 cannot be installed.
How can I solve this problem.? Thanks~

**Comment by melancholy12** [comment]
scv                                2.0.0
scvelo                             0.2.4
scvi                               0.6.8
scvi-colab                         0.11.0
scvi-tools                         0.7.1
scArches                           0.5.9

**Comment by Koncopd** [comment]
Looks like your scvi-tools version is too old, please try with ~0.14.
Feel fre to reopen if still doesn't work.
