### ISSUE TITLE
Fail to establish scpoli model

### ISSUE THREAD

**Issue by melancholy12** [theislab/scarches#203]
early_stopping_kwargs = {
    "early_stopping_metric": "val_prototype_loss",
    "mode": "min",
    "threshold": 0,
    "patience": 20,
    "reduce_lr": True,
    "lr_patience": 13,
    "lr_factor": 0.1,
}

condition_key = 'sample'
cell_type_key = ['cell_type']
query = ['new16']

scpoli_model = scPoli(
    adata=adata_ref,
    condition_key=condition_key,
    cell_type_keys=cell_type_key,
    embedding_dim=3,
    latent_dim=10,
)      

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[38], line 1
----> 1 scpoli_model = scPoli(
      2     adata=adata_ref,
      3     condition_key=condition_key,
      4     cell_type_keys=cell_type_key,
      5     embedding_dim=3,
      6     latent_dim=10,
      7 )

TypeError: __init__() got an unexpected keyword argument 'condition_key'

**Comment by cdedonno** [comment]
If you're using the latest version you need to use the argument `condition_keys`, not `condition_key`.

**Comment by cdedonno** [comment]
Closing because of no response
