### ISSUE TITLE
the difference between scPoli and scANVI

### ISSUE THREAD

**Issue by YawnC** [theislab/scarches#216]
Just curious, since they both based on cVAE, with cell-type data as conditioning input, is there any difference between their backbones or algorithms?

**Comment by moinfar** [comment]
Hi,

Yes.
There are so many differences in the modeling, which results in a significant difference in the model's performance.
I can mention some differences (not all):
  1. scPoli uses prototypes per cell type and employs a metric learning approach to form the latent space.
  2. scPoli maps the covariates in a continuous latent space that reveals sample level variation.
I suggest reading the paper for more details.
