### ISSUE TITLE
More detailed training logs

### ISSUE THREAD

**Issue by Nusob888** [theislab/scarches#222]
Hi, 

Would it be possible to update the logs to state the use of CPU or GPU. I can see that you have a GPU check within the trainer, but it does not tell the user which is being used. For me, I had assumed the model was just much slower than the other models within scArches, but then realised that my cuda was not being detected. Even though I now have ensured my torch is detecting cuda, I still have no idea if the trainer is using the gpu.

This could be a major source of headache for people on different institutional HPC set ups

Many thanks

**Comment by chelseabright96** [comment]
Hi, this has been added now for all models in PR #221. Thanks for the recommendation!

**Comment by Nusob888** [comment]
Amazing! thank you!
