### ISSUE TITLE
scanpy compatibility

### ISSUE THREAD

**Issue by kylekimler** [theislab/scarches#23]
Hi,

I'm getting package compatibility issues between scArches and Scanpy. Do you have a recommended version of scanpy to go with scArches? I was hoping to use a recent SCtransform branch. But its dependencies are >version than py3.7

Thanks!

**Comment by M0hammadL** [comment]
hi @kylekimler , there should not be any issues with scanpy and searches. I think the problem raised due to python version which scanpy required higher version than searches (<3.8)

**Comment by kylekimler** [comment]
Hi @M0hammadL , yeah. I was just hoping to use a newer scanpy branch with scArches.
