### ISSUE TITLE
Can trVAE in scarches be applied to perturbation prediction? 

### ISSUE THREAD

**Issue by weizhiting** [theislab/scarches#239]
Hi, 
In the original [trVAE](https://github.com/theislab/trVAE?tab=readme-ov-file), trVAE can be used to perturbation prediction. I wonder whether trVAE in [scarches](https://docs.scarches.org/en/latest/trvae_surgery_pipeline.html#) can be applied to perturbation prediction?  In scarches demo case, trVAE was used to remove batch effect.

**Comment by M0hammadL** [comment]
hi Chelsea, could you please add a tutorial similar to this one https://github.com/theislab/trVAE/blob/master/examples/trVAE_Haber.ipynb using the Python version of trvae as in here https://github.com/theislab/scarches/blob/master/notebooks/trvae_surgery_pipeline.ipynb

**Comment by weizhiting** [comment]
Thanks for your reply.
