### ISSUE TITLE
Effects of cell cycle, mitochondrial counts

### ISSUE THREAD

**Issue by macrinalobo** [theislab/scarches#24]
Thank you for a great tool. I'm wondering how you recommend dealing with cell cycle / mt count effects on data. Do you recommend regressing out the effect prior to training ? And is any particular loss function better post regression? Thanks a lot.

**Comment by M0hammadL** [comment]
@macrinalobo  Hi and thx :) I have never tried to regress for MT genes when feeding them to these kinds of models and this will change the gene expression so I would not do it here unless there is a clear biological insight and motive to do this? is this the case in your application?

Mo

**Comment by macrinalobo** [comment]
Thanks for the reply!

I computed cell cycle and projected onto the UMAP obtained after nearest neighbor on the latent space and it seemed like the phases grouped together on the UMAP. This was no longer the case when I regressed out cell cycle and used 'sse' instead of 'nb'. But I was wondering if that was the correct approach or not.

**Comment by M0hammadL** [comment]
did you expect them to group together? regarding the nb and see loss both of them have different results and one has to evaluate them on a case by case manner.

**Comment by macrinalobo** [comment]
No I don't expect them to group together. 
It didn't seem correct to me  to run loss_fn = 'nb' (or zinb) post regressing out variables ( mt_fraction, cell cycle ) but doesn't seem wrong to run use sse. Is that correct ? 

Also, completely unrelated but do you have tips on how to use use the latent space for studying differential expression of inputs ? 

Thanks a lot.

**Comment by M0hammadL** [comment]
> No I don't expect them to group together.
> It didn't seem correct to me to run loss_fn = 'nb' (or zinb) post regressing out variables ( mt_fraction, cell cycle ) but doesn't seem wrong to run use sse. Is that correct ?
Yes for NB and ZINB you need raw count data but for sse your flexible to change the 
data nad preprocess it as you like.

> 
> Also, completely unrelated but do you have tips on how to use use the latent space for studying differential expression of inputs ?

You could perform clustering on latent space and then use those clusters as groups in DE testing? 
> 
> Thanks a lot.

**Comment by macrinalobo** [comment]
But then I would be using normalized data for Differential expression testing which would be sensitive to the "condition" effects, right ? Wouldn't that be a problem ? 

To combat that, I was thinking of something along the lines of seeing which variables in the latent space are active and seeing what genes those turn on by passing through the decoder ( with the appropriate condition ). Is that completely ridiculous ?
