### ISSUE TITLE
Inquiry for hlca_map_classify.ipynb

### ISSUE THREAD

**Issue by numakuT** [theislab/scarches#253]
Hi,

Thank you for the great work.
I have encountered an issue in the hlca_map_classify.ipynb.

I cannot proceed due to an error in the "Load reference model and set relevant query variables" section as follows.

surgery_model = sca.models.SCANVI.load_query_data(
    adata_query,
    ref_model_dir,
    freeze_dropout=True,
)

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In [39], line 1
----> 1 surgery_model = sca.models.SCANVI.load_query_data(
      2     adata_query,
      3     ref_model_dir,
      4     freeze_dropout=True,
      5 )

File /opt/conda/lib/python3.10/site-packages/scvi/model/base/_archesmixin.py:122, in ArchesMixin.load_query_data(cls, adata, reference_model, inplace_subset_query_vars, accelerator, device, unfrozen, freeze_dropout, freeze_expression, freeze_decoder_first_layer, freeze_batchnorm_encoder, freeze_batchnorm_decoder, freeze_classifier)
    116 if _SETUP_ARGS_KEY not in registry:
    117     raise ValueError(
    118         "Saved model does not contain original setup inputs. "
    119         "Cannot load the original setup."
    120     )
--> 122 setup_method = getattr(cls, registry[_SETUP_METHOD_NAME])
    123 setup_method(
    124     adata,
    125     source_registry=registry,
   (...)
    128     **registry[_SETUP_ARGS_KEY],
    129 )
    131 model = _initialize_model(cls, adata, attr_dict)

KeyError: 'setup_method_name'

I would appreciate it if you could advice me on how to trouble shoot it. Thank you for your help.

Best regards,
TN

**Comment by Koncopd** [comment]
Hi, there was a similar problem recently https://github.com/theislab/scarches/issues/252

**Comment by numakuT** [comment]
Thanks!
