### ISSUE TITLE
ExpiMap tutorial error

### ISSUE THREAD

**Issue by YuliaInn** [theislab/scarches#256]
I've been following the [ExpiMap tutorial ](https://docs.scarches.org/en/latest/expimap_surgery_pipeline_advanced.html)but faced the following issue. I loaded the query data from Kang et al. and tried to train the model using it:

```
url = 'https://drive.google.com/uc?id=1t3oMuUfueUz_caLm5jmaEYjBxVNSsfxG'
output = 'kang_tutorial.h5ad'
gdown.download(url, output, quiet=False)
kang = sc.read('kang_tutorial.h5ad')[:, adata.var_names].copy()
kang.obs['study'] = 'Kang'
kang.uns['terms'] = adata.uns['terms']

q_intr_cvae = sca.models.EXPIMAP.load_query_data(kang, intr_cvae,
                                                 unfreeze_ext=True,
                                                 new_n_ext=3,
                                                 new_n_ext_m=1,
                                                 new_ext_mask=query_mask.T,
                                                 new_soft_ext_mask=True,
                                                 use_hsic=True,
                                                 hsic_one_vs_all=True
                                                )

q_intr_cvae.train(
    n_epochs=250,
    alpha_epoch_anneal=120,
    alpha_kl=0.22,
    weight_decay=0.,
    alpha_l1=0.96,
    gamma_ext=0.7,
    gamma_epoch_anneal=50,
    beta=3.,
    seed=2020,
    use_early_stopping=False
)

```

I got this error:
ValueError: Expected parameter loc (Tensor of shape (128, 455)) of distribution Normal(loc: torch.Size([128, 455]), scale: torch.Size([128, 455])) to satisfy the constraint Real(), but found invalid values:
tensor([[nan, nan, nan, nan, nan, nan, nan,  ..., nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan,  ..., nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan,  ..., nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan,  ..., nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan,  ..., nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan,  ..., nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan,  ..., nan, nan, nan, nan, nan, nan, nan],
        ...,
        [nan, nan, nan, nan, nan, nan, nan,  ..., nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan,  ..., nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan,  ..., nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan,  ..., nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan,  ..., nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan,  ..., nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan,  ..., nan, nan, nan, nan, nan, nan, nan]],
       grad_fn=<CatBackward0>)

Knowing that the data should contain count values, I checked it:

`kang.X`

array([[  0.,   0.,   0.,   0.,   0.,   0.,   1., ...,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0., ...,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [  1.,   0.,   0.,   0.,   0.,   0.,   0., ...,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0., ...,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [  3.,   0.,   0.,   1.,   0.,   0.,   1., ...,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [  1.,   0.,   0.,   0.,   0.,   0.,   0., ...,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0., ...,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       ...,
       [ 10.,   0.,   0.,   0.,   0.,   0.,   0., ...,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [  3.,   0.,   0.,   0.,   0.,   0.,   0., ...,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [264.,   0.,   0.,   0.,   0.,   1.,   0., ...,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [  7.,   0.,   0.,   0.,   0.,   0.,   0., ...,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [ 16.,   0.,   0.,   0.,   0.,   0.,   0., ...,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [  4.,   0.,   0.,   0.,   0.,   0.,   0., ...,   0.,   0.,   0.,
          0.,   0.,   0.,   0.],
       [ 10.,   0.,   0.,   0.,   0.,   0.,   0., ...,   0.,   0.,   0.,
          0.,   0.,   0.,   0.]], dtype=float32)

Why do I get this error?
Also, looks like the kang dataset has different dimensions than in the tutorial. Now it has 3690 cells while in the tutorial it had 1972

**Comment by Koncopd** [comment]
> Now it has 3690 cells while in the tutorial it had 1972

It is variables (genes), not cells. 
Looks like something went wrong in the previous steps, hard to say what.

**Comment by YuliaInn** [comment]
@Koncopd Sorry, I meant to write genes. In the previous steps, I also followed the tutorial, pre-processed the ref data, added reactome GPs and removed the IFN-beta related ones as well as B cells, and then trained the model on ref data. 
What do you think could go wrong? The model initialization? Training?
Why does Kang data have more genes now than in the tutorial? Should I keep only highly variable genes?

thanks!

**Comment by YuliaInn** [comment]
I encountered an issue with the HVG selection step, but after rerunning the preprocessing, everything worked smoothly. I'll go ahead and close the issue. Apologies for the trouble!
