### ISSUE TITLE
example pancreas dataset not there 

### ISSUE THREAD

**Issue by LisaSikkema** [theislab/scarches#32]
Hi! In your example notebook "pancreas_pipeline.ipynb" the file pancreas_normalized_hvg.h5ad is loaded from "./tests/data/pancreas_normalized_hvg.h5ad". However, the file is not there in the repo. Is it possible to upload it again?

**Comment by LisaSikkema** [comment]
okay seems like the readthedocs is actually more up to date
https://scarches.readthedocs.io/en/latest/pancreas_pipeline.html
it uses
adata = sca.datasets.pancreas()
maybe good to update the notebook on the github as well?

**Comment by M0hammadL** [comment]
hey, we went back to the previous version, now everything should work. The newest version had bugs to we had to remove it.

**Comment by LisaSikkema** [comment]
okay so I should remove my current scArches and re-install? or are you just talking about the notebook?
