### ISSUE TITLE
Cuda out of memory!

### ISSUE THREAD

**Issue by farnoush-shh** [theislab/scarches#41]

**Comment by farnoush-shh** [comment]
Hi,
when I am using SCANVI and using default early stopping:


sca.dataset.setup_anndata(reference_adata, batch_key=condition_key, labels_key=cell_type_key)
INFO     Using batches from adata.obs["Patient"]                                             
INFO     Using labels from adata.obs["cell_type"]                                            
INFO     Using data from adata.X                                                             
INFO     Computing library size prior per batch                                              
INFO     Successfully registered anndata object containing 139699 cells, 33538 vars, 18      
         batches, 12 labels, and 0 proteins. Also registered 0 extra categorical covariates  
         and 0 extra continuous covariates.                                                  
INFO     Please do not further modify adata until model is trained.  


vae = sca.models.SCANVI(
    reference_adata,
    "Unknown",
    n_layers=2,
    n_latent=15,
    use_cuda=True,
    encode_covariates=True,
    deeply_inject_covariates=False,
    use_layer_norm="both",
    use_batch_norm="none",
)
​
print("Labelled Indices: ", len(vae._labeled_indices))
print("Unlabelled Indices: ", len(vae._unlabeled_indices))
Labelled Indices:  139699
Unlabelled Indices:  0




vae.train(
    n_epochs_unsupervised=vae_epochs,
    n_epochs_semisupervised=scanvi_epochs,
    unsupervised_trainer_kwargs=dict(early_stopping_kwargs=early_stopping_kwargs_1),
    semisupervised_trainer_kwargs=dict(metrics_to_monitor=["elbo", "accuracy"],
                                       early_stopping_kwargs=early_stopping_kwargs_scanvi),
    frequency=1
)
INFO     Training Unsupervised Trainer for 200 epochs.                                       
INFO     Training SemiSupervised Trainer for 100 epochs.                                     
INFO     KL warmup phase exceeds overall training phaseIf your applications rely on the      
         posterior quality, consider training for more epochs or reducing the kl warmup.     
INFO     KL warmup for 400 epochs                                                            
Training...:  55%|█████▌    | 110/200 [58:03<47:27, 31.64s/it] INFO     Reducing LR on epoch 110.                                                           
Training...: 100%|██████████| 200/200 [1:45:35<00:00, 31.68s/it]
INFO     Training is still in warming up phase. If your applications rely on the posterior   
         quality, consider training for more epochs or reducing the kl warmup.               
INFO     Training time:  3648 s. / 200 epochs                                                
INFO     KL warmup phase exceeds overall training phaseIf your applications rely on the      
         posterior quality, consider training for more epochs or reducing the kl warmup.     
INFO     KL warmup for 400 epochs                                                            
Training...:   0%|          | 0/100 [00:26<?, ?it/s]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-24-8527e2ea3a17> in <module>
      5     semisupervised_trainer_kwargs=dict(metrics_to_monitor=["elbo", "accuracy"],
      6                                        early_stopping_kwargs=early_stopping_kwargs_scanvi),
----> 7     frequency=1
      8 )

~/anaconda3/envs/epigenf2/lib/python3.7/site-packages/scvi/model/scanvi.py in train(self, n_epochs_unsupervised, n_epochs_semisupervised, train_base_model, train_size, test_size, lr, n_epochs_kl_warmup, n_iter_kl_warmup, frequency, unsupervised_trainer_kwargs, semisupervised_trainer_kwargs, unsupervised_train_kwargs, semisupervised_train_kwargs)
    309         self.trainer.train(
    310             n_epochs=n_epochs_semisupervised,
--> 311             **semisupervised_train_kwargs,
    312         )
    313         self.is_trained_ = True

~/anaconda3/envs/epigenf2/lib/python3.7/site-packages/scvi/core/trainers/trainer.py in train(self, n_epochs, lr, eps, params, **extras_kwargs)
    194                 self.on_iteration_begin()
    195                 # Update the model's parameters after seeing the data
--> 196                 self.on_training_loop(tensors_dict)
    197                 # Checks the training status, ensures no nan loss
    198                 self.on_iteration_end()

~/anaconda3/envs/epigenf2/lib/python3.7/site-packages/scvi/core/trainers/trainer.py in on_training_loop(self, tensors_dict)
    212 
    213     def on_training_loop(self, tensors_dict):
--> 214         self.current_loss = loss = self.loss(*tensors_dict)
    215         self.optimizer.zero_grad()
    216         loss.backward()

~/anaconda3/envs/epigenf2/lib/python3.7/site-packages/scvi/core/trainers/annotation.py in loss(self, tensors_all, tensors_labelled)
    224 
    225     def loss(self, tensors_all, tensors_labelled=None):
--> 226         loss = super().loss(tensors_all, feed_labels=False)
    227         if tensors_labelled is not None:
    228             sample_batch = tensors_labelled[_CONSTANTS.X_KEY]

~/anaconda3/envs/epigenf2/lib/python3.7/site-packages/scvi/core/trainers/inference.py in loss(self, tensors, feed_labels)
    133             y = None
    134         reconst_loss, kl_divergence_local, kl_divergence_global = self.model(
--> 135             sample_batch, local_l_mean, local_l_var, batch_index, y
    136         )
    137         loss = (

~/anaconda3/envs/epigenf2/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/anaconda3/envs/epigenf2/lib/python3.7/site-packages/scvi/core/modules/scanvae.py in forward(self, x, local_l_mean, local_l_var, batch_index, y)
    217         pz1_m, pz1_v = self.decoder_z1_z2(z2, ys)
    218 
--> 219         reconst_loss = self.get_reconstruction_loss(x, px_rate, px_r, px_dropout)
    220 
    221         # KL Divergence

~/anaconda3/envs/epigenf2/lib/python3.7/site-packages/scvi/core/modules/vae.py in get_reconstruction_loss(self, x, px_rate, px_r, px_dropout, **kwargs)
    325                     mu=px_rate, theta=px_r, zi_logits=px_dropout
    326                 )
--> 327                 .log_prob(x)
    328                 .sum(dim=-1)
    329             )

~/anaconda3/envs/epigenf2/lib/python3.7/site-packages/scvi/core/distributions/_negative_binomial.py in log_prob(self, value)
    434                 UserWarning,
    435             )
--> 436         return log_zinb_positive(value, self.mu, self.theta, self.zi_logits, eps=1e-08)
    437 
    438 

~/anaconda3/envs/epigenf2/lib/python3.7/site-packages/scvi/core/distributions/_negative_binomial.py in log_zinb_positive(x, mu, theta, pi, eps)
     60     mul_case_non_zero = torch.mul((x > eps).type(torch.float32), case_non_zero)
     61 
---> 62     res = mul_case_zero + mul_case_non_zero
     63 
     64     return res

RuntimeError: CUDA out of memory. Tried to allocate 18.00 MiB (GPU 0; 11.78 GiB total capacity; 9.66 GiB already allocated; 7.31 MiB free; 10.62 GiB reserved in total by PyTorch)



grateful for your help.

**Comment by Cottoneyejoe95** [comment]
Hi, sorry for the late reply. Do you still have the error? The error message seems like you also ran other stuff in parallel?

**Comment by farnoush-shh** [comment]
Hi, no problem. 
This problem arises because the cuda version and pytorch was not compatible.
Solved!

**Comment by mukundctx** [comment]
@farnoush-shh i'm running into similar errors. If you still remember, what versions of CUDA and torch made it work?
