### ISSUE TITLE
scarches google colab and tqdm~=4.49.0 installation

### ISSUE THREAD

**Issue by rdesantis90** [theislab/scarches#44]
Hi,
I am trying to install scarches on google colab.
But I get this error even when I try to specify the indicated tqdm version, can you help me fix it?

ERROR: scarches 0.3.4 has requirement tqdm~=4.49.0, but you'll have tqdm 4.56.0 which is incompatible.

Thank you in advance 
Best

**Comment by Koncopd** [comment]
Hi, @rdesantis90 
The new version should work fine.
