### ISSUE TITLE
Update to scvi-tools>=0.9.0

### ISSUE THREAD

**Issue by adamgayoso** [theislab/scarches#51]
Hi all,

It would be great to update to use the new scvi-tools version. We have a tutorial [here](https://docs.scvi-tools.org/en/stable/user_guide/notebooks/scarches_scvi_tools.html) that should show everything necessary to change. From your end, it's just going to be these minor API changes in the train method. We also don't have accuracy tracked for scanvi, but do have the classification loss.

**Comment by M0hammadL** [comment]
Hi Adam, we are working on this, @Koncopd could you please see the necessary changes we need to make and the we submit a PR and @adamgayoso  reviewers it?

**Comment by Koncopd** [comment]
Yes, i'll do.

**Comment by adamgayoso** [comment]
This should happen ASAP hopefully. There are breaking changes in pytorch lightning that we fixed in newer versions, but will break the code here.

**Comment by Koncopd** [comment]
Yes, the only things that need to be changed are the notebooks which use scvi-tools. The problem is that it is not easy to figure out how to translate all the past arguments to the new ones.

**Comment by adamgayoso** [comment]
Not all will be exactly translatable (some of the early stopping with scanvi). I would suggest to look out the tutorial on [our site](https://docs.scvi-tools.org/en/stable/user_guide/notebooks/scarches_scvi_tools.html) and feel free to ping me about certain details.

**Comment by M0hammadL** [comment]
@Cottoneyejoe95  could you please update it functions to use latest veraion of scvitoola

**Comment by Cottoneyejoe95** [comment]
@adamgayoso Hi Adam, I updated the notebooks for scvi and scanvi to work with scvi-tools 0.12.0. Would be cool if you have a look and tell me if I should call something in a different way.
However, for the TotalVI notebook I always get an error during surgery and I guess already during the init of the surgery model. Couldnt find the reason for that, since it's pretty much the same code as you are using in your totalvi notebook. Maybe you could help here?

**Comment by adamgayoso** [comment]
@Cottoneyejoe95 where can I find the new notebooks?

**Comment by Cottoneyejoe95** [comment]
@adamgayoso Thanks for your quick reply. I reran all notebooks with lightning 1.3 and it worked pretty flawless. You can find the notebooks here:

SCVI/SCANVI:
https://github.com/theislab/scarches/blob/master/notebooks/scvi_surgery_pipeline.ipynb
https://github.com/theislab/scarches/blob/master/notebooks/scanvi_surgery_pipeline.ipynb

TOTALVI:
https://github.com/theislab/scarches/blob/master/notebooks/totalvi_surgery_pipeline.ipynb

**Comment by M0hammadL** [comment]
@Cottoneyejoe95  have you tested trvae too with new version?

**Comment by Cottoneyejoe95** [comment]
@M0hammadL Yes everything runs for me.

**Comment by M0hammadL** [comment]
@Cottoneyejoe95  did you make a new release and update pip? if not please release

**Comment by adamgayoso** [comment]
Do the results look a bit worse on these compared to our tutorials?

**Comment by adamgayoso** [comment]
early stopping might be too aggresive

**Comment by Cottoneyejoe95** [comment]
Made a new release and also updated the scvi/scanvi notebooks to use almost the same training params as proposed on the scvi-tools documentation to be consistent.
