### ISSUE TITLE
Using GPU in parallel

### ISSUE THREAD

**Issue by ccruizm** [theislab/scarches#59]
Good day!

I have a question whether is possible to set the parameters to use several GPU in parallel to train the models that support this feature.

Btw, `use_gpu` parameter does not work in the last version of `scarches` (v0.3.5). Took me some time to find that the new flag is `use_cuda` (saw it in one of the issues raised before)     ;)

Thanks in advance!

**Comment by M0hammadL** [comment]
Hi @ccruizm  thanks for pointing this out.
