### ISSUE TITLE
no version under scarches.__version__

### ISSUE THREAD

**Issue by LisaSikkema** [theislab/scarches#60]
Hi! It would be nice if you guys would store the scarches version under `scarches.__version__` so that I can check the version from within python.

**Comment by M0hammadL** [comment]
Hi @Koncopd  could you please add this?

**Comment by M0hammadL** [comment]
@Koncopd  can you also fix this?

**Comment by Koncopd** [comment]
@M0hammadL yes, i forgot about this, i will fix.

**Comment by Koncopd** [comment]
fixed
