### ISSUE TITLE
Problem with installation (Fedora 25)

### ISSUE THREAD

**Issue by mbuttner** [theislab/scarches#7]
I tried to install scarches in a conda environment using
 `pip install -U scarches`
And I received the following error message:
```
Collecting scarches
  Downloading scArches-0.1.2-py3-none-any.whl (50 kB)
     |████████████████████████████████| 50 kB 1.5 MB/s 
Collecting keras==2.2.4
  Using cached Keras-2.2.4-py2.py3-none-any.whl (312 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow==1.15.2 (from scarches) (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==1.15.2 (from scarches)
```

**Comment by Naghipourfar** [comment]
Hi @mbuttner, 

Could you please say which python version are you using? I believe that TensorFlow 1.15.2 works with Python 3.6.x or Python 3.7.x and it does not have a distribution for Python 3.8.x and Python3.5.x (or lower).

Thanks

**Comment by mbuttner** [comment]
Thank you for the clarification! I have set up my python environment anew and indeed use Python 3.8.5. 
It would be awesome to see scarches working for Python 3.8.*, but I will downgrade then.

**Comment by M0hammadL** [comment]
@mbuttner @Naghipourfar  agree we have to make it compatible with 3.8 too, we will release a Pytorch version soon that is also compatible with the latest python. sorry fo inconvenience

**Comment by mbuttner** [comment]
No worries and thanks again for the quick response!
