### ISSUE TITLE
Importance of selecting a comprehensive reference

### ISSUE THREAD

**Issue by Lesdormis** [theislab/scarches#70]
Dear scarches developers,

I was wondering that how important to select a good and comprehensive dataset as a reference to build the model upon?
If the reference missed some celltypes that exist in the latter dataset, can the model still capture the heterogeneous?

Thanks,

**Comment by M0hammadL** [comment]
HI @Lesdormis 

sorry for the late reply :) 

I would say the reference building is really important and one has to pay attention to multiple things: 
- The reference should include multiple batches in order for the model to understand the notion of batch effect (have at least 2-3 studies in there)

> the integration and the model that you integrate the reference is also important, try scvi first. 
> If the reference missed some celltypes that exist in the latter dataset, can the model still capture the heterogeneous?
> 

yeah this possible for sure for unseen states such as disease

**Comment by Lesdormis** [comment]
Thanks for the reply!
