### ISSUE TITLE
Should size_factors be logarithmized?

### ISSUE THREAD

**Issue by Koncopd** [theislab/scarches#77]
@Cottoneyejoe95 I have noticed that now `size_factors` are not logarimized, before `np.log` was applied to them (it is so still in my branch). What is the correct way actually?

**Comment by M0hammadL** [comment]
I don't think they have to be logarithmized, before (and now)it was just output of sc.po. Normalize_per_cell

**Comment by Cottoneyejoe95** [comment]
Hi @Koncopd yes that was a mistake in an old state. It worked with log. siz_factors but it makes more sense without log and the loss is also more stable.
