### ISSUE TITLE
documentation - minor typos/errors

### ISSUE THREAD

**Issue by bkmartinjr** [theislab/scarches#8]
Minor issues I noted while reading the current documentation:

1. about.html:  Where To Start has a formatting issue with the pancreas pipeline link.
2. api/data.html:
    * Params for normalize_hvg() are misformatted.
    * "here" link in scarches.data.read() is a dead link
3. api/utils.html: param formatting for scarches.util.label_encoder() is bad
4. api/zenodo.html: upload_adaptor() and others -- missing capitalization on first sentence ("upload"), and other scattered accidental capitalization, eg, "Creates A deposition...."
5. latest/model_sharing.html:  "toturial" misspelled
6. latest/pancrease_pipeline.html: "a new query stuy ...", study is misspelled
7. the `conditions` param for sca.models.scArches is documented as an 'int', but it really a list per the source code.

**Comment by M0hammadL** [comment]
thank you Bruce for pointing these out.  I addressed all the points in this issue
