### ISSUE TITLE
Training parameters to reproduce the result

### ISSUE THREAD

**Issue by xiaoyanLi629** [theislab/scarches#84]
Hello,

I am wondering do you have the parameters for training the model so that I could reproduce the result. For example, the random seed, training iterations, learning rate etc.

Thanks,
Xiaoyan

**Comment by M0hammadL** [comment]
Hey, please see supplementary tables  https://static-content.springer.com/esm/art%3A10.1038%2Fs41587-021-01001-7/MediaObjects/41587_2021_1001_MOESM1_ESM.pdf
