### ISSUE TITLE
Expanding SCANVI model with new cell types

### ISSUE THREAD

**Issue by chbeltz** [theislab/scarches#85]
As per the docs: ["If you have a new cell-type label that is in the query data but not in reference and you want to use this in the training query you will get an error! We will fix this in future releases"](https://scarches.readthedocs.io/en/latest/training_tips.html)

When trying to do transfer learning to build a cell type classifier, it would make sense that one would sooner or later reach the point where a new dataset contains a new cell type. With the model unable to accustom new labels, one of the (IMO) most interesting possible applications architecture surgery seems to go out the window.

Is a solution to this still in planning? Does the problem problem lie with scArches or does it (which I suspect) lie with the way SCANVI sets up its classifier?

Thanks!

Related: #35

**Comment by M0hammadL** [comment]
Hey, sorry for this, we are working on this but it will be  take some time will reopen this once released
