### ISSUE TITLE
suggestions for docs improvements

### ISSUE THREAD

**Issue by bkmartinjr** [theislab/scarches#9]
Couple of suggested improvements in the docs, based upon a first read:
* reference API docs for important API used in the examples (eg, sca.operate, scc.ann.*, etc)
* a sketch of the various models, highlighting their behavior and when it is appropriate to try them
* examples of appropriate use of `normalize_hvg()` and the semantics of `size_factors` (required by subsequent network training).

**Comment by M0hammadL** [comment]
Hi Bruce we added an example dor data preprocessing [here](https://scarches.readthedocs.io/en/latest/zenodo_intestine.html) also added a few training tips [here](https://scarches.readthedocs.io/en/latest/training_tips.html)

**Comment by bkmartinjr** [comment]
Thanks @M0hammadL - will read.  

Looking at the Zenodo Intestine notebook, it [continues to mention](https://scarches.readthedocs.io/en/latest/zenodo_intestine.html#create-scArches-network-from-scratch) the `n_conditions` param for `sca.models.scArches`, when I think it should reference `conditions`.
