### ISSUE TITLE
type object 'SCANVI' has no attribute 'from_scvi_model'

### ISSUE THREAD

**Issue by XingTang2014** [theislab/scarches#97]
I was running the example from scanvi_surgery_pipeline.ipynb and got the error.

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-13-6cec5b2d5e1b> in <module>
> ----> 1 scanvae = sca.models.SCANVI.from_scvi_model(vae, "Unknown")
> 
> AttributeError: type object 'SCANVI' has no attribute 'from_scvi_model'
> 
> print("Labelled Indices: ", len(scanvae._labeled_indices))

Below is my session info.

> Click to view session information
> -----
> anndata             0.7.8
> gdown               4.3.1
> matplotlib          3.3.4
> numpy               1.19.5
> scanpy              1.7.2
> scarches            NA
> scvi                0.8.1
> session_info        1.0.0
> torch               1.8.1+cu111
> -----
> Click to view modules imported as dependencies
> -----
> IPython             7.16.1
> jupyter_client      6.1.11
> jupyter_core        4.7.1
> jupyterlab          3.2.4
> notebook            6.4.6
> -----
> Python 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01) [GCC 9.3.0]
> Linux-4.14.252-131.483.amzn1.x86_64-x86_64-with-glibc2.9
> -----
> Session information updated at 2022-02-21 23:53

Any suggestions?

**Comment by Koncopd** [comment]
Please upgrade scarches and scvi-tools-
