### ISSUE TITLE
ModuleNotFoundError:No module named 'scvi.data.setup_annadata'

### ISSUE THREAD

**Issue by aster-ww** [theislab/scarches#98]
cannot find function "setup_annadata" in package scvi.data

**Comment by Koncopd** [comment]
I have added the fix to pip, please upgrade scarches.

**Comment by xuebaliang** [comment]
I meet the same problem, but I find that the "dataset" file does not update and this function does not appear, so how can I fix it?

**Comment by xuebaliang** [comment]
Yes, I have installed the lasted version. But I still meet the following error:
Traceback (most recent call last):
  File "test_scarches.py", line 38, in <module>
    sca.dataset.setup_anndata(source_adata, batch_key=condition_key, labels_key=cell_type_key)
AttributeError: module 'scarches.dataset' has no attribute 'setup_anndata'

How can I fix it? It seems that the package "scvi" does not have the function, is it?

**Comment by Koncopd** [comment]
Ok, i see, thx for pointing.
This thing we import from scvi, i think it was discontinued starting from scvi 0.15.0. You could check the scvi docs on how to do it properly now, the correct approach now is:
`sca.models.SCVI.setup_anndata(...)`

I have updated our tutorials also with the correct way.

**Comment by xuebaliang** [comment]
We just installed the scvi 0.14 version, but it still does not work, can you check it or write the specific function in your github's files?

**Comment by Koncopd** [comment]
But why do you wan't to use the deprecated function? Just use replacement as described now in scarches tutorials.
Or pin both scvi 0.14 and scarches 0.5.0 (not 0.5.1).
